#define A index_type
#define B return
#define D noexcept
#define E address_traits
#define F typename
#define G static_cast
#define H size_t
#define I template
#define J const
#define K detail
#define M nullptr
#define N static
#define O ManagerT
#define P granule_size
#define Q constexpr
#define R BlockState
#define S total_size
#define V void
#define W DefaultAddressTraits
#define X false
#define Y uint8_t
#define Z BlockStateBase
#define j using
#define k no_block
#define m base
#define o DiagnosticAction
#define q ManagerHeader
#define z uint64_t
#define AA _last_error
#define AD hdr
#define AE PmmError
#define AF ViolationType
#define AG sizeof
#define AH _initialized
#define AI reinterpret_cast
#define AJ _backend
#define AK static_assert
#define AL std
#define AM result
#define AN bool
#define AO inline
#define AP thread_policy
#define AQ is_null
#define AR base_ptr
#define AS logging_policy
#define AU get_next_offset
#define AV pptr
#define AW node_type
#define AX find_domain_by_name_unlocked
#define AY namespace
#define AZ raw_blk
#define Aa pstringview
#define Ab node_pptr
#define Ac block_at
#define Ad PPtr
#define Ae manager_type
#define Af operator
#define Ag numeric_limits
#define Ah validate_block_index
#define Ai kForestBindingDirectRoot
#define Aj kBlockHdrGranules
#define Ak uint32_t
#define Al _size
#define Am free_tree_root
#define An other
#define Ao Block
#define Ap pmm
#define Aq first_block_offset
#define Ar get_weight
#define As blk_idx
#define At idx
#define Au struct
#define Av _file_handle
#define Aw unique_lock_type
#define Ax shared_lock_type
#define Ay set_parent_offset_of
#define Az free_block_tree
#define BA kForestDomainFlagSystem
#define BB last_block_offset
#define BC register_domain_unlocked
#define BD new_data_gran
#define BE forest_registry_root_unlocked
#define BF forest_domain
#define BG char
#define BH kGranSz
#define BI byte_off
#define BJ IndexT
#define BK kBlkHdrGran
#define BL pptr_set_parent
#define BM new_size
#define BN this
#define BO resolve_data
#define BP block_count
#define BQ _map_handle
#define BR forest_domain_root_index_unlocked
#define BS update_node
#define BT node_idx
#define BU blk_raw
#define BV uint16_t
#define BW root_offset
#define BX parent
#define BY forest_registry
#define BZ root_idx
#define Ba new_node
#define Bb used_size
#define Bc offset
#define Bd set_right_offset_of
#define Be free_count
#define Bf manager_header_offset_bytes_v
#define Bg NoAction
#define Bh AllocatedBlock
#define Bi true
#define Bj kForestDomainNameCapacity
#define Bk int16_t
#define Bl ManagerAccess
#define Bm PersistMemoryManager
#define Bn kServiceNameDomainRoot
#define Bo kBlockHeaderGranules_t
#define Bp set_left_offset_of
#define Bq VerifyResult
#define Br validate_bootstrap_invariants_unlocked
#define Bs user_size
#define Bt forest_domain_descriptor
#define Bu storage_backend
#define Bv pptr_get_right
#define Bw convertible_to
#define Bx FieldTag
#define By on_allocation_failure
#define Bz find_domain_by_binding_unlocked
#define CA get_parent_offset
#define CB _data_idx
#define CC raw
#define CD size_bytes
#define CE forest_domain_policy
#define CF binding_id
#define CG INVALID_HANDLE_VALUE
#define CH set_prev_offset_of
#define CI pptr_get_left
#define CJ own_idx
#define CK image_version
#define CL blk_ptr
#define CM allocator
#define CN FreeTreeStale
#define CO BlockStateInconsistent
#define CP name
#define CQ get_right_offset
#define CR _owns_memory
#define CS HeaderCorruption
#define CT Domain
#define CU old_data_gran
#define CV expected_count
#define CW _buffer
#define CX InvalidPointer
#define CY _mutex
#define CZ resolve_node
#define Ca get_left_offset
#define Cb _current_idx
#define Cc get_header
#define Cd kSystemDomainSymbols
#define Ce entry_count
#define Cf alloc_count
#define Cg on_corruption_detected
#define Ch domain
#define Ci write_block_field
#define Cj root_index
#define Ck resolve_unchecked
#define Cl forest_domain_root_index_ptr_unlocked
#define Cm cast_from_raw
#define Cn StaticStorage
#define Co state_from_raw
#define Cp root_index_ptr
#define Cq binding_kind
#define Cr typed_guard
#define Cs kSystemDomainRegistry
#define Ct kSystemDomainFreeTree
#define Cu PMM_BLOCK_INDEX_FIELD
#define Cv HeapStorage
#define Cw CoalescingBlock
#define Cx find_block_from_user_ptr
#define Cy set_next_offset_of
#define Cz read_block_field
#define DA avl_rebalance_up
#define DB kForestRegistryMagic
#define DC kCurrentImageVersion
#define DD symbol_offset
#define DE bootstrap_forest_registry_unlocked
#define DF public
#define DG next_offset
#define DH auto
#define DI set_avl_height_of
#define DJ forest_domain_ops
#define DK FreeBlockNotInAVL
#define DL FreeBlock
#define DM resolve_granule_ptr
#define DN kForestRegistryVersion
#define DO intern_symbol_unlocked
#define DP get_root_offset
#define DQ get_domain_root_offset
#define DR bytes_to_granules_t
#define DS FreeBlockRemovedAVL
#define DT BlockParentOffsetField
#define DU _base
#define DV root
#define DW domain_count
#define DX value
#define DY tree_node
#define DZ pptr_set_left
#define Da pptr_no_block
#define Db kNodeReadOnly
#define Dc get_node_type
#define Dd additional_bytes
#define De ValidPmmAddressTraits
#define Df IndexType
#define Dg BlockRightOffsetField
#define Dh Base
#define Di make_pptr_from_raw
#define Dj ForestDomainRecord
#define Dk AvlInorderIterator
#define Dl kNullIdx_v
#define Dm data
#define Dn BlockRootOffsetField
#define Do BlockLeftOffsetField
#define Dp successor
#define Dq manager_header_at
#define Dr lock_block_permanent_unlocked
#define Ds ensure_capacity
#define Dt class
#define Du AllocatorPolicy
#define Dv set_field_of
#define Dw get_field_of
#define Dx field_offset
#define Dy OutOfMemory
#define Dz NodeUpdateFn
#define EA AvlFreeTree
#define EB visited_count
#define EC total_gran
#define ED set_forest_domain_root_index_unlocked
#define EE kBlockSize
#define EF block_field_value_t
#define EG backend
#define EH BlockAvlHeightField
#define EI AvlUpdateHeightOnly
#define EJ reg
#define EK blk
#define EL raw_user_ptr_from_pptr
#define EM kForestBindingFreeTree
#define EN else
#define EO delete
#define EP ptrdiff_t
#define EQ for_each_free_block_inorder
#define ER _capacity
#define ES is_canonical_allocated_block_header
#define ET _length
#define EU FreeBlockTreePolicyForTraitsConcept
#define EV BlockNodeTypeField
#define EW symbol
#define EX crc32_accumulate_byte
#define EY MMapStorage
#define EZ ForestDomainViewDescriptor
#define Ea kGranuleSize
#define Eb initial_size
#define Ec deallocate
#define Ed avl_height
#define Ee BackendError
#define Ef resolve_checked
#define Eg requires
#define Eh explicit
#define Ei uintptr_t
#define Ej data_granules
#define Ek cur
#define El bootstrap_system_symbols_unlocked
#define Em avl_set_child
#define En block_total_granules
#define Eo lock
#define Ep rec
#define Eq pptr_set_right
#define Er next_blk
#define Es is_initialized
#define Et SplittingBlock
#define Eu verify_forest_registry_unlocked
#define Ev validate_or_bootstrap_forest_registry_unlocked
#define Ew private
#define Ex pallocator
#define Ey new_idx
#define Ez new_data_gran_alloc
#define FA new_cap
#define FB domains
#define FC ForestDomainViewOps
#define FD CloseHandle
#define FE BufferSize
#define FF BlockWeightField
#define FG kDefaultGrowDenominator
#define FH is_trivially_copyable_v
#define FI get_header_c
#define FJ forest_domain_name_fits
#define FK data_gran
#define FL cand_addr
#define FM kLegacyUnversionedImageVersion
#define FN find_domain_by_symbol_unlocked
#define FO set_root_offset_of
#define FP view
#define FQ symbol_domain_record_unlocked
#define FR set_weight_of
#define FS pptr_get_parent
#define FU next_idx
#define FV new_user_size
#define FW min_user_offset
#define FX get_prev_offset
#define FY cand_idx
#define FZ raw_block_user_ptr_from_pptr
#define Fa while
#define Fb verify_free_tree_node
#define Fc pptr_type
#define Fd kFreeBlkIdxLayout
#define Fe kDefaultGrowNumerator
#define Ff kBlockHdrByteSize
#define Fg is_block_header_linked_in_canonical_chain
#define Fh init_fields
#define Fi byte_off_to_idx_t
#define Fj allocate_unlocked
#define Fk _binding_id
#define Fl ForestRegistryMissing
#define Fm kMinMemorySize
#define Fo get_avl_height
#define Fp block_raw_mut_ptr_from_pptr
#define Fq _mapped
#define Fr PersistMemoryManagerConcept
#define Fs last_blk_raw
#define Ft granules
#define Fu is_storage_backend_v
#define Fv block_field_offset_v
#define Fw add
#define Fx ForestDomainRegistry
#define Fy BlockPrevOffsetField
#define Fz BlockNextOffsetField
#define GA is_supported_image_version
#define GB BlockT
#define GC BlockFieldLayout
#define GD weight_val
#define GE right
#define GF parent_offset
#define GG new_raw
#define GH forest_domain_view_policy
#define GI find_best_fit
#define GJ entries
#define GK descriptor
#define GL default
#define GM deallocate_unlocked
#define GN c_str
#define GO block_idx_from_pptr
#define GP blk_off
#define GQ base_addr
#define GR allocate_from_block
#define GS BlockPPtr
#define GT Aborted
#define GU state_as
#define GV psview_pptr
#define GW new_base
#define GX kMgrHdrGranules
#define GY kFreeBlkIdx
#define GZ insert
#define Ga existing
#define Gb config
#define Gc NodePPtr
#define Gd InvalidSize
#define Ge free_tree_block_granules
#define Gf ForestDomainFlagsMissing
#define Gg set_tree_idx_field
#define Gh ptr_to_granule_idx
#define Gi get_tree_idx_field
#define Gj free_tree_less_key
#define Gk avl_balance_factor
#define Gl BlockTreeNodeProxy
#define Gm right_p
#define Gn right_offset
#define Go resolve
#define Gp ptr
#define Gq old_next_blk
#define Gr new_free_idx
#define Gs block_raw_ptr_from_pptr
#define Gt UnsupportedImageVersion
#define Gu target
#define Gv memset
#define Gw kNodeReadWrite
#define Gx assert
#define Gy ValueT
#define Gz view_base
#define HA used_gran
#define HB par_p
#define HC new_child
#define HD magic
#define HE kMaxForestDomains
#define HF avl_subtree_count
#define HG avl_clear_subtree
#define HH value_type
#define HI snapshot
#define HJ pmap_fnv1a
#define HK data_bytes
#define HL coalescing
#define HM allocate
#define HN alloc_size
#define HO _idx
#define HP TreeNode
#define HQ key
#define HR image_version_requires_migration
#define HS prev_offset
#define HT owns_memory
#define HU new_size_li
#define HV length
#define HW left_p
#define HX left_offset
#define HY kMaxDiagnosticEntries
#define HZ kGranSzCreate
#define Ha index
#define Hb config_logging_policy
#define Hc concept
#define Hd PersistMemoryTypedApi
#define He BlockFieldTraits
#define Hf BasicConfig
#define Hg memory_order_acquire
#define Hh left
#define Hi BlockFieldByteAccess
#define Hj tmp_path
#define Hk succ_idx
#define Hl set_root_offset
#define Hm root_val
#define Hn required
#define Ho old_size
#define Hp next_binding_id
#define Hq new_count
#define Hr kSystemTypeForestDomainRecord
#define Hs is_valid_user_offset_unlocked
#define Ht filename
#define Hu curr_next
#define Hv cand_off
#define Hw callback
#define Hx SharedMutexLock
#define Hy ForestDomainOps
#define Hz memcpy
#define IA mark_entries
#define IB kHdrGranules
#define IC avl_min_node
#define ID RecoveryMode
#define IE verify_block_states
#define IF find_domain_by_name
#define IG domain_key
#define IH compute_image_crc32
#define II aligned
#define IJ _ptr
#define IK ForestDomainMissing
#define IL ForestDomainDescriptorForKey
#define IM FILE_MAP_ALL_ACCESS
#define IN set_tree_field
#define IO set_avl_height
#define IP obj
#define IQ max
#define IR get_tree_field
#define IS forest_domain_validate_node
#define IT data_gran_need
#define IU bytes
#define IV break
#define IW allocate_typed
#define IX NotInitialized
#define IY verify_linked_list
#define IZ size
#define Ia manager_index_type
#define Ib SmallAddressTraits
#define Ic LargeAddressTraits
#define Id CreateFileMappingA
#define Ie CacheManagerConfig
#define Ig succ_parent
#define Ii new_blk_ptr
#define Ik is_free_raw
#define Il init_layout
#define Im block_index
#define In old_next
#define Io Overflow
#define Ip validate_node
#define Iq symbol_policy
#define Ir read_stat
#define Is pstring
#define It prev
#define Iu node
#define Iw granules_to_bytes
#define Ix forest_verify
#define Iz flags
#define JA finalize_coalesce
#define JB file_size
#define JC extra_idx
#define JD avl_update_height
#define JF DWORD
#define JG ConfigT
#define JH AddressTraits
#define JK verify_free_tree
#define JL value_hex_digits
#define JM set_weight
#define JN set_node_type_of
#define JO set_height
#define JP reset_avl_fields
#define JQ remove
#define JR public_raw
#define JS mutex_type
#define JT kMagic
#define JU is_allocated_raw
#define JV field_value_type
#define JW domain_type_hash
#define JX deallocate_typed
#define JY avl_rotate_right
#define JZ StateT
#define Ja ManagerLayoutOps
#define Jb verify_state
#define Jc initial_root
#define Je blk_new_next
#define Jf AccessPolicy
#define Jg verify_counters
#define Jh unsigned
#define Ji type
#define Jj succ_raw
#define Jk set_next_offset
#define Jl raw_addr
#define Jm prev_idx
#define Jn pmap_write_name
#define Jo old_data
#define Jp offsetof
#define Js iterator
#define Jt get_domain_root
#define Jx blk_next
#define Jy avl_rotate_left
#define KA MgrT
#define KB GranuleMismatch
#define KD Callback
#define KE weight
#define KG strcmp
#define KH splitting
#define KI set_child
#define KJ pptr_make
#define KL old_blk_raw
#define KM new_dat_idx
#define KN needed_gran
#define KO needed
#define KR growth
#define KU do_expand
#define KV compare_key
#define KW block_idx_t
#define KZ GranuleSz
#define Kk version
#define Kp rem_idx
#define Kr raw_off
#define LA fprintf
