/**
 * @file pmm_multi_threaded_heap.h
 * @brief PMM preset: MultiThreadedHeap — SharedMutexLock + HeapStorage, grow 25% (PersistentDataConfig)
 *
 * Thin single-header preset file for the PersistMemoryManager library
 * (https://github.com/netkeep80/PersistMemoryManager).
 *
 * Includes the full PMM library (pmm.h) and defines the MultiThreadedHeap
 * preset alias in pmm::presets for convenience.
 *
 * Usage:
 * @code
 *   #include "pmm_multi_threaded_heap.h"
 *
 *   pmm::presets::MultiThreadedHeap::create(64 * 1024);
 *   void* ptr = pmm::presets::MultiThreadedHeap::allocate(256);
 *   pmm::presets::MultiThreadedHeap::deallocate(ptr);
 *
 *   // Persistence (save/load):
 *   pmm::save_manager<pmm::presets::MultiThreadedHeap>("heap.dat");
 *   pmm::load_manager_from_file<pmm::presets::MultiThreadedHeap>("heap.dat");
 * @endcode
 *
 * Generated by scripts/generate-single-headers.sh
 */

#pragma once

#include "pmm.h"

namespace pmm
{
namespace presets
{

using MultiThreadedHeap = PersistMemoryManager<PersistentDataConfig, 0>;

} // namespace presets
} // namespace pmm
