/**
 * @file pmm_single_threaded_heap.h
 * @brief PMM preset: SingleThreadedHeap — NoLock + HeapStorage, grow 25% (CacheManagerConfig)
 *
 * Thin single-header preset file for the PersistMemoryManager library
 * (https://github.com/netkeep80/PersistMemoryManager).
 *
 * Includes the full PMM library (pmm.h) and defines the SingleThreadedHeap
 * preset alias in pmm::presets for convenience.
 *
 * Usage:
 * @code
 *   #include "pmm_single_threaded_heap.h"
 *
 *   pmm::presets::SingleThreadedHeap::create(64 * 1024);
 *   void* ptr = pmm::presets::SingleThreadedHeap::allocate(256);
 *   pmm::presets::SingleThreadedHeap::deallocate(ptr);
 *
 *   // Persistence (save/load):
 *   pmm::save_manager<pmm::presets::SingleThreadedHeap>("heap.dat");
 *   pmm::load_manager_from_file<pmm::presets::SingleThreadedHeap>("heap.dat");
 * @endcode
 *
 * Generated by scripts/generate-single-headers.sh
 */

#pragma once

#include "pmm.h"

namespace pmm
{
namespace presets
{

using SingleThreadedHeap = PersistMemoryManager<CacheManagerConfig, 0>;

} // namespace presets
} // namespace pmm
