/**
 * @file pmm_industrial_db_heap.h
 * @brief PMM preset: IndustrialDBHeap — SharedMutexLock + HeapStorage, grow 100% (IndustrialDBConfig)
 *
 * Thin single-header preset file for the PersistMemoryManager library
 * (https://github.com/netkeep80/PersistMemoryManager).
 *
 * Includes the full PMM library (pmm.h) and defines the IndustrialDBHeap
 * preset alias in pmm::presets for convenience.
 *
 * Usage:
 * @code
 *   #include "pmm_industrial_db_heap.h"
 *
 *   pmm::presets::IndustrialDBHeap::create(64 * 1024);
 *   void* ptr = pmm::presets::IndustrialDBHeap::allocate(256);
 *   pmm::presets::IndustrialDBHeap::deallocate(ptr);
 *
 *   // Persistence (save/load):
 *   pmm::save_manager<pmm::presets::IndustrialDBHeap>("heap.dat");
 *   pmm::load_manager_from_file<pmm::presets::IndustrialDBHeap>("heap.dat");
 * @endcode
 *
 * Generated by scripts/generate-single-headers.sh
 */

#pragma once

#include "pmm.h"

namespace pmm
{
namespace presets
{

using IndustrialDBHeap = PersistMemoryManager<IndustrialDBConfig, 0>;

} // namespace presets
} // namespace pmm
