/**
 * @file pmm_large_db_heap.h
 * @brief PMM preset: LargeDBHeap — SharedMutexLock + HeapStorage/64B granule/64-bit index (LargeDBConfig)
 *
 * Thin single-header preset file for the PersistMemoryManager library
 * (https://github.com/netkeep80/PersistMemoryManager).
 *
 * Includes the full PMM library (pmm.h) and defines the LargeDBHeap
 * preset alias in pmm::presets for convenience.
 *
 * Usage:
 * @code
 *   #include "pmm_large_db_heap.h"
 *
 *   pmm::presets::LargeDBHeap::create(64 * 1024);
 *   void* ptr = pmm::presets::LargeDBHeap::allocate(256);
 *   pmm::presets::LargeDBHeap::deallocate(ptr);
 *
 *   // Persistence (save/load):
 *   pmm::save_manager<pmm::presets::LargeDBHeap>("heap.dat");
 *   pmm::load_manager_from_file<pmm::presets::LargeDBHeap>("heap.dat");
 * @endcode
 *
 * Generated by scripts/generate-single-headers.sh
 */

#pragma once

#include "pmm.h"

namespace pmm
{
namespace presets
{

using LargeDBHeap = PersistMemoryManager<LargeDBConfig, 0>;

} // namespace presets
} // namespace pmm
