/**
 * @file pmm_embedded_static_heap.h
 * @brief PMM preset: EmbeddedStaticHeap — NoLock + StaticStorage/16B granule (EmbeddedStaticConfig)
 *
 * Thin single-header preset file for the PersistMemoryManager library
 * (https://github.com/netkeep80/PersistMemoryManager).
 *
 * Includes the full PMM library (pmm.h) and defines the EmbeddedStaticHeap
 * preset alias in pmm::presets for convenience.
 *
 * Usage:
 * @code
 *   #include "pmm_embedded_static_heap.h"
 *
 *   pmm::presets::EmbeddedStaticHeap::create(64 * 1024);
 *   void* ptr = pmm::presets::EmbeddedStaticHeap::allocate(256);
 *   pmm::presets::EmbeddedStaticHeap::deallocate(ptr);
 *
 *   // Persistence (save/load):
 *   pmm::save_manager<pmm::presets::EmbeddedStaticHeap>("heap.dat");
 *   pmm::load_manager_from_file<pmm::presets::EmbeddedStaticHeap>("heap.dat");
 * @endcode
 *
 * Generated by scripts/generate-single-headers.sh
 */

#pragma once

#include "pmm.h"

namespace pmm
{
namespace presets
{

template <std::size_t BufferSize = 4096>
using EmbeddedStaticHeap = PersistMemoryManager<EmbeddedStaticConfig<BufferSize>, 0>;

} // namespace presets
} // namespace pmm
