/**
 * @file pmm_embedded_heap.h
 * @brief PMM preset: EmbeddedHeap — NoLock + HeapStorage, grow 50% (EmbeddedManagerConfig)
 *
 * Thin single-header preset file for the PersistMemoryManager library
 * (https://github.com/netkeep80/PersistMemoryManager).
 *
 * Includes the full PMM library (pmm.h) and defines the EmbeddedHeap
 * preset alias in pmm::presets for convenience.
 *
 * Usage:
 * @code
 *   #include "pmm_embedded_heap.h"
 *
 *   pmm::presets::EmbeddedHeap::create(64 * 1024);
 *   void* ptr = pmm::presets::EmbeddedHeap::allocate(256);
 *   pmm::presets::EmbeddedHeap::deallocate(ptr);
 *
 *   // Persistence (save/load):
 *   pmm::save_manager<pmm::presets::EmbeddedHeap>("heap.dat");
 *   pmm::load_manager_from_file<pmm::presets::EmbeddedHeap>("heap.dat");
 * @endcode
 *
 * Generated by scripts/generate-single-headers.sh
 */

#pragma once

#include "pmm.h"

namespace pmm
{
namespace presets
{

using EmbeddedHeap = PersistMemoryManager<EmbeddedManagerConfig, 0>;

} // namespace presets
} // namespace pmm
